In [1]:
import numpy as np
import pandas as pd
import altair as alt

In [2]:
data = pd.read_csv("denver-1.nov.csv")

In [3]:
data.head()

,raw_row_number,date,time,location,lat,lng,district,precinct,type,disposition,arrest_made,citation_issued,warning_issued,outcome
0,1,2012-11-13,00:02:22,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
1,16,2012-11-29,00:25:01,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,Party Advised,False,False,False,NaN
2,72,2012-11-23,22:58:10,4830 S HOLLAND WAY,39.630666,-105.102551,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
3,121,2012-11-27,17:48:33,4885 S QUEBEC ST,39.626174,-104.904062,3,324,pedestrian,In Service,False,False,False,NaN
4,138,2012-11-14,23:46:58,W LAYTON AVE / S WADSWORTH BLVD,39.630150,-105.081693,4,423,vehicular,Party Advised,False,False,False,NaN

In [7]:
data["disposition"].unique()

array(['K - Street Check Completed', 'Party Advised', 'In Service',
       'Warning Issued', 'L - Clearance', 'T - Citation Issued',
       'Arrest Made', 'File Only', 'O - Veh Released to Owner',
       'UTL / Unfounded / Unsuccessful', 'K - Street Check Completed,L -',
       'Back Up / Cover Car', 'No Police Needed',
       'K - Street Check Completed,T -', 'Detox Van', 'Report Made',
       'Y - Broadcast', 'X - Exchanged Info', '2 - Alarm False',
       'Vehicle Towed', 'CIT Report', 'None', 'Z - Test',
       '1 - Alarm RP On Scene', 'Evidence / Property',
       '1 - Alarm RP On Scene,K - Stre', 'Supervisor Cancelled Inc',
       '3 - Alarm Good', 'GOA', 'Detox Van,K - Street Check Com',
       'Arrest Made,T - Citation Issue', 'Report Made,T - Citation Issue',
       'K - Street Check Completed,Par', 'Arrest Made,K - Street Check C',
       'Vehicle Towed,Warning Issued'], dtype=object)

In [8]:
type(data.loc[0,"time"])

str

In [9]:
def late_at_night(time_stamp):
    hour = int(time_stamp[0:2])
    if hour < 4 or hour > 21:
        return True
    else:
        return False

In [10]:
late_at_night(data.loc[0,"time"])

True

In [11]:
data["Late_At_Night"] = data["time"].apply(late_at_night)

In [12]:
data.head()

,raw_row_number,date,time,location,lat,lng,district,precinct,type,disposition,arrest_made,citation_issued,warning_issued,outcome,Late_At_Night
0,1,2012-11-13,00:02:22,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,K - Street Check Completed,False,False,False,NaN,True
1,16,2012-11-29,00:25:01,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,Party Advised,False,False,False,NaN,True
2,72,2012-11-23,22:58:10,4830 S HOLLAND WAY,39.630666,-105.102551,4,423,vehicular,K - Street Check Completed,False,False,False,NaN,True
3,121,2012-11-27,17:48:33,4885 S QUEBEC ST,39.626174,-104.904062,3,324,pedestrian,In Service,False,False,False,NaN,False
4,138,2012-11-14,23:46:58,W LAYTON AVE / S WADSWORTH BLVD,39.630150,-105.081693,4,423,vehicular,Party Advised,False,False,False,NaN,True

In [13]:
type(data.loc[0,"arrest_made"])

numpy.bool_

In [14]:
def fix_booleans(boolean):
    if boolean == True:
        return 1
    else:
        return 0

In [15]:
data["arrest_made"] = data["arrest_made"].apply(fix_booleans)

In [16]:
data["citation_issued"] = data["citation_issued"].apply(fix_booleans)

In [17]:
data["warning_issued"] = data["warning_issued"].apply(fix_booleans)

In [18]:
data.head()

,raw_row_number,date,time,location,lat,lng,district,precinct,type,disposition,arrest_made,citation_issued,warning_issued,outcome,Late_At_Night
0,1,2012-11-13,00:02:22,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,K - Street Check Completed,0,0,0,NaN,True
1,16,2012-11-29,00:25:01,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,Party Advised,0,0,0,NaN,True
2,72,2012-11-23,22:58:10,4830 S HOLLAND WAY,39.630666,-105.102551,4,423,vehicular,K - Street Check Completed,0,0,0,NaN,True
3,121,2012-11-27,17:48:33,4885 S QUEBEC ST,39.626174,-104.904062,3,324,pedestrian,In Service,0,0,0,NaN,False
4,138,2012-11-14,23:46:58,W LAYTON AVE / S WADSWORTH BLVD,39.630150,-105.081693,4,423,vehicular,Party Advised,0,0,0,NaN,True

In [50]:
gb = data.groupby("Late_At_Night").agg({"arrest_made":np.mean, "citation_issued":np.mean, "warning_issued":np.mean})

In [51]:
gb

               arrest_made  citation_issued  warning_issued
Late_At_Night
False             0.129315         0.196378        0.102999
True              0.186507         0.131049        0.129989

In [52]:
gb.reset_index(inplace=True)

In [53]:
gb["arrest_made"] = gb["arrest_made"].apply(lambda x: round(x*100,2))

In [54]:
gb["citation_issued"] = gb["citation_issued"].apply(lambda x: round(x*100,2))

In [55]:
gb["warning_issued"] = gb["warning_issued"].apply(lambda x: round(x*100,2))

In [56]:
c1 = alt.Chart(gb, title = "Percent of Stops with an Arrest Based on Time of Day").mark_bar().encode(x="Late_At_Night", 
                                     y="arrest_made", 
                                     color="Late_At_Night", 
                                     tooltip = ["arrest_made"])
c2 = alt.Chart(gb, title = "Percent of Stops with a Citation Based on Time of Day").mark_bar().encode(x="Late_At_Night", 
                                     y="citation_issued", 
                                     color="Late_At_Night", 
                                     tooltip = ["citation_issued"])
c3 = alt.Chart(gb, title = "Percent of Stops with a Warning Based on Time of Day").mark_bar().encode(x="Late_At_Night", 
                                     y="warning_issued", 
                                     color="Late_At_Night", 
                                     tooltip = ["warning_issued"])
c1 | c2 | c3

alt.HConcatChart(...)